version: '2'

services:

  veritask:
    build: .
    volumes:
      - ./:/home/veritask
    ports:
      - 9000:9000
    links:
      - mongo
      - fuseki
    restart: always
    command: target/universal/stage/bin/veritask -Dplay.crypto.secret=abcdefghijk -Dconfig.resource=prod.conf

  mongo:
    image: mongo
    volumes:
      - ./../database:/data/db
    restart: always

  fuseki:
    image: stain/jena-fuseki
    ports:
      - "3030:3030"
    restart: always
