version: '2'

services:

  mongo:
    image: mongo
    volumes:
      - ./../database:/data/db
    network_mode: "host"

  fuseki:
    image: stain/jena-fuseki
    ports:
      - "3030:3030"
    network_mode: "host"
